### ISSUE TITLE
Final semicolon ; when defining context variables in structural directives should be optional

### ISSUE THREAD

**Issue by kherock** [ghaschel/vscode-angular-html#15] opened 2018-11-22 11:24 UTC
![image](https://user-images.githubusercontent.com/4993980/48899922-ef899180-ee1e-11e8-8f7f-db599e50cb16.png)

I can't remember if I started using this extension before 0.0.31 came out, but I'm now noticing syntax highlighting breaking pretty spectacularly in some of the my `*ngIf` and `*ngFor` directives. Hopefully it's simple to fix.

**Comment by ghaschel** [comment] 2018-11-22 14:59
Omg that looks terrible.

I'm looking into this. But i fear it might have something to do with the built in js pattern recognition.

Thank you for reporting it =]

**Comment by ghaschel** [comment] 2018-11-22 18:14
Just for clarifying: It has to do with the built in pattern. I will have to adapt the built in one so that it can work with angular template expressions the proper way. It wasn't happening before because the plugin was restructured recently.

It is now actually using a js pattern recognition

**Comment by ghaschel** [comment] 2018-11-22 18:59
I adapted the pattern. It is now built in the plugin itself, not using the vscode one anymore.

The issue is fixed in [0.0.33](https://github.com/ghaschel/vscode-angular-html/commit/19cd237d85f4436e615572d8571b0bd60e0b5340), although there is still a lot of improvements and cleaning to do in that pattern.

Let me know if it still happening, or if my any means it returns to happen in the upcoming versions after the improvements. =]

**Comment by kherock** [comment] 2018-11-24 16:38
Hey sorry I disappeared, things seem to be fine now - thanks for the quick fix 😊

**Closed as completed** 2018-11-24 17:36 UTC
Labels: bug
